#!/bin/bash

set -x
set -e

RUBY_VERSION="$1"

# Use the right Ruby /without/ rbenv
ruby_dir=$(dirname "$(RBENV_VERSION=$RUBY_VERSION rbenv which ruby)")
export PATH=$ruby_dir:$PATH

# Announce who we are
ruby -v

export GEM_HOME="$(pwd)/.gem-$1"
export GEM_PATH="$GEM_HOME:$GEM_PATH"

gem install bundler
bundle install

# Go ham
rake
